services:
  mysql:
    image: mysql:8.4
    container_name: study-mate-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study_mate_db
    ports:
      - "5001:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
